In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7801, 6681, 5853, 4304],
 [7801, 6681, 5853, 5951],
 [7801, 8368, 5853, 2718],
 [4263, 7792, 4719, 4285, 4408],
 [4263, 7792, 4719, 4285, 5719],
 [5416, 7801, 564, 5853, 8330],
 [6434, 3248, 4414, 4285]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7801 6681 5853 4304]
 [   0    0    0    0 7801 6681 5853 5951]
 [   0    0    0    0 7801 8368 5853 2718]
 [   0    0    0 4263 7792 4719 4285 4408]
 [   0    0    0 4263 7792 4719 4285 5719]
 [   0    0    0 5416 7801  564 5853 8330]
 [   0    0    0    0 6434 3248 4414 4285]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 238ms/step


array([[[ 0.02193486,  0.01189723, -0.02357266,  0.03905027,
         -0.0032716 ,  0.03028176, -0.03215528,  0.01813746,
         -0.02644536,  0.0090773 ],
        [ 0.02193486,  0.01189723, -0.02357266,  0.03905027,
         -0.0032716 ,  0.03028176, -0.03215528,  0.01813746,
         -0.02644536,  0.0090773 ],
        [ 0.02193486,  0.01189723, -0.02357266,  0.03905027,
         -0.0032716 ,  0.03028176, -0.03215528,  0.01813746,
         -0.02644536,  0.0090773 ],
        [ 0.02193486,  0.01189723, -0.02357266,  0.03905027,
         -0.0032716 ,  0.03028176, -0.03215528,  0.01813746,
         -0.02644536,  0.0090773 ],
        [ 0.02599685,  0.01643021,  0.04478837,  0.02826785,
          0.00060285,  0.03254907,  0.03663827, -0.00612738,
          0.00795528, -0.02739987],
        [ 0.04085766, -0.01929654, -0.01727662, -0.03491869,
         -0.00202283,  0.03324706, -0.04624308, -0.02633498,
          0.00759854, -0.00165942],
        [ 0.00198893, -0.01250041,  0.02072987, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7801, 6681, 5853, 4304])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 42ms/step


array([[ 0.02193486,  0.01189723, -0.02357266,  0.03905027, -0.0032716 ,
         0.03028176, -0.03215528,  0.01813746, -0.02644536,  0.0090773 ],
       [ 0.02193486,  0.01189723, -0.02357266,  0.03905027, -0.0032716 ,
         0.03028176, -0.03215528,  0.01813746, -0.02644536,  0.0090773 ],
       [ 0.02193486,  0.01189723, -0.02357266,  0.03905027, -0.0032716 ,
         0.03028176, -0.03215528,  0.01813746, -0.02644536,  0.0090773 ],
       [ 0.02193486,  0.01189723, -0.02357266,  0.03905027, -0.0032716 ,
         0.03028176, -0.03215528,  0.01813746, -0.02644536,  0.0090773 ],
       [ 0.02599685,  0.01643021,  0.04478837,  0.02826785,  0.00060285,
         0.03254907,  0.03663827, -0.00612738,  0.00795528, -0.02739987],
       [ 0.04085766, -0.01929654, -0.01727662, -0.03491869, -0.00202283,
         0.03324706, -0.04624308, -0.02633498,  0.00759854, -0.00165942],
       [ 0.00198893, -0.01250041,  0.02072987, -0.0056349 , -0.04191325,
         0.0453079 ,  0.04962299,  0.02503249